.github/CODEOWNERS, .github/dependabot.yml, .github/release-drafter.yml, .github/workflows/release-drafter.yml, .gitignore, .mvn/extensions.xml, .mvn/maven.config, CONTRIBUTING.adoc, Jenkinsfile, LICENSE, README.adoc, pom.xml, src/main/java/io/jenkins/plugins/remotingopentelemetry/CheckIfRunWithEngineCommand.java, src/main/java/io/jenkins/plugins/remotingopentelemetry/RemotingOpenTelemetryComputerListener.java, src/test/java/io/jenkins/plugins/remotingopentelemetry/CheckIfRunWithEngineCommandTest.java
close #1 
Create project skeleton, I refer to
- https://www.jenkins.io/doc/developer/plugin-development/
- https://www.jenkins.io/doc/developer/publishing/
I use the following names.
- `remoting-opentelemetry` for the artifactId
- `remotingopentelemetry` for the package name
- `Jenkins Remoting monitoring with OpenTelemetry Plugin` for the plugin name
`CONTRIBUTING.adoc` is the copy of https://github.com/jenkinsci/.github/blob/master/CONTRIBUTING.md but I removed some sections and changed it into AsciiDoc format.
=> Create project skeleton

pom.xml
Following the Jenkins style guide, I'll remove "Jenkins" from the plugin name.
See also [the comment in the Jira](https://issues.jenkins.io/browse/HOSTING-1110?focusedCommentId=409984&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-409984)
=> Remove "Jenkins" from plugin name

pom.xml
Remove a build plugin that statically selects the build target java version.
=> Remove a build plugin that statically selects the build target java version

.github/ISSUE_TEMPLATE/3-other.md
link #16 
Add the "other" issue template.
An unknown type of issue should suggest how we can close the issue.
=> add other issue template

README.adoc, README.md
close #17 
Add Slack and project page link to README.adoc
=> Add Slack and project page link to README

.github/ISSUE_TEMPLATE/2-feature-request.md
close #28 
Change the default label of the feature request issue to "enhancement"
=> Update the default label of the feature request issue

.github/pull_request_template.md
close #16 
Update PR template checklist to keep the PR an independent deliverable.
=> Add some checklist items to PR template  

README.adoc, example/README.adoc, example/docker-compose.yaml, example/otel-collector/otel-collector-config.yaml, example/prometheus/prometheus.yml, jenkins-plugin/src/main/java/io/jenkins/plugins/remotingopentelemetry/RemotingOpenTelemetryComputerListener.java, jenkins-plugin/src/main/java/io/jenkins/plugins/remotingopentelemetry/RemotingOpenTelemetryConfiguration.java, jenkins-plugin/src/test/java/io/jenkins/plugins/remotingopentelemetry/commands/SyncMonitoringEngineCommandTest.java, jenkins-plugin/src/test/java/io/jenkins/plugins/remotingopentelemetry/commands/UpdateMonitoringEngineConfigCommandTest.java, monitoring-engine/src/main/java/io/jenkins/plugins/remotingopentelemetry/engine/EngineConfiguration.java, monitoring-engine/src/main/java/io/jenkins/plugins/remotingopentelemetry/engine/MonitoringEngine.java, monitoring-engine/src/main/java/io/jenkins/plugins/remotingopentelemetry/engine/OpenTelemetryProxy.java, monitoring-engine/src/main/java/io/jenkins/plugins/remotingopentelemetry/engine/RemotingMetricExporterProvider.java, monitoring-engine/src/main/java/io/jenkins/plugins/remotingopentelemetry/engine/RemotingResourceProvider.java, monitoring-engine/src/main/java/io/jenkins/plugins/remotingopentelemetry/engine/metric/GarbageCollectorMXBeanMetric.java, monitoring-engine/src/main/java/io/jenkins/plugins/remotingopentelemetry/engine/metric/MemoryMXBeanMetric.java, monitoring-engine/src/main/java/io/jenkins/plugins/remotingopentelemetry/engine/metric/MemoryPoolMXBeanMetric.java, monitoring-engine/src/main/java/io/jenkins/plugins/remotingopentelemetry/engine/metric/OperatingSystemMXBeanMetric.java, monitoring-engine/src/main/java/io/jenkins/plugins/remotingopentelemetry/engine/semconv/OpenTelemetryMetricsSemanticConventions.java, monitoring-engine/src/main/java/io/jenkins/plugins/remotingopentelemetry/engine/span/JnlpEndpointResolvingSpan.java, monitoring-engine/src/test/java/io/jenkins/plugins/remotingopentelemetry/engine/MonitoringEngineTest.java, monitoring-engine/src/test/java/io/jenkins/plugins/remotingopentelemetry/engine/listener/RemoteEngineListenerTest.java, monitoring-engine/src/test/java/io/jenkins/plugins/remotingopentelemetry/engine/listener/RootListenerTest.java, monitoring-engine/src/test/java/io/jenkins/plugins/remotingopentelemetry/engine/span/JnlpInitializationSpanTest.java
close #51 
Enable to collect metrics.
See README.adoc for details.
=> collect metrics

jenkins-plugin/src/main/java/io/jenkins/plugins/remotingopentelemetry/RemotingOpenTelemetryConfiguration.java, jenkins-plugin/src/main/resources/io/jenkins/plugins/remotingopentelemetry/RemotingOpenTelemetryConfiguration/config.jelly, monitoring-engine/src/main/java/io/jenkins/plugins/remotingopentelemetry/engine/EngineConfiguration.java, monitoring-engine/src/main/java/io/jenkins/plugins/remotingopentelemetry/engine/MonitoringEngine.java, monitoring-engine/src/main/java/io/jenkins/plugins/remotingopentelemetry/engine/OpenTelemetryProxy.java, monitoring-engine/src/main/java/io/jenkins/plugins/remotingopentelemetry/engine/metric/GarbageCollectorMXBeanMetric.java, monitoring-engine/src/main/java/io/jenkins/plugins/remotingopentelemetry/engine/metric/MemoryMXBeanMetric.java, monitoring-engine/src/main/java/io/jenkins/plugins/remotingopentelemetry/engine/metric/MemoryPoolMXBeanMetric.java, monitoring-engine/src/main/java/io/jenkins/plugins/remotingopentelemetry/engine/metric/OperatingSystemMXBeanMetric.java, monitoring-engine/src/test/java/io/jenkins/plugins/remotingopentelemetry/engine/metric/OperatingSystemMXBeanMetricTest.java
close #60 
Enable to select what kind of metrics to collect
_System Metrics Group_ is a set of metrics that start with `system.*`
_Process Metrics Group_ is a set of metrics that start with `process.*`
_JVM Metrics Group_ is a set of metrics that start with `runtime.jvm.*`
See README.adoc for all metrics to collect. 
we should add help text to explain each option (#63)
=> Configure what kind of metrics to collect

monitoring-engine/src/main/java/io/jenkins/plugins/remotingopentelemetry/engine/log/OpenTelemetryLogHandler.java
Spotbug reports errors and this fixed it.
=> Fix spotbug error

jenkins-plugin/pom.xml
Jenkins plugin module doesn't depend on the monitoring engine anymore.
I removed the dependency.
=> remove unused dependency

pom.xml
Fix GitHub repository in pom.xml
We need to merge this to deploy our maven repo.
=> Fix GitHub repository

.github/workflows/cd.yml
Setup for [JEP 229](https://github.com/jenkinsci/jep/tree/master/jep/229).
=> JEP 229 setup

monitoring-engine/pom.xml
We don't need to declare perfmark-api dependency explicitly anymore.
close #47
=> Remove perfmark-api dependency

pom.xml
Add a description tag to parent pom.xml to show the description of this project properly in the update center.
=> Add a description tag to parent pom.xml

CONTRIBUTING.adoc, README.adoc, monitoring-engine/src/main/java/io/jenkins/plugins/remotingopentelemetry/engine/MonitoringEngine.java, monitoring-engine/src/main/java/io/jenkins/plugins/remotingopentelemetry/engine/metric/FilesystemMetric.java, monitoring-engine/src/main/java/io/jenkins/plugins/remotingopentelemetry/engine/semconv/OpenTelemetryMetricsSemanticConventions.java, monitoring-engine/src/test/java/io/jenkins/plugins/remotingopentelemetry/engine/metric/OperatingSystemMXBeanMetricTest.java
Collect filesystem metrics ([OpenTelmetry specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/system-metrics.md#systemfilesystem---filesystem-metrics)).
- get mount info by reading `/proc/mounts`
- use [File#getUsableSpace](https://docs.oracle.com/javase/8/docs/api/java/io/File.html#getUsableSpace--) and [File#getTotalSpace](https://docs.oracle.com/javase/8/docs/api/java/io/File.html#getTotalSpace--) to get free disk space and total disk space of each filesystem.
- thus, Linux only so far. (leave #83)
close: #72 
leave: #83
=> Filesystem metrics (Linux only)

README.adoc
Download the monitoring engine from the Jenkins Maven repository.
=> Fix "Getting started": Download the monitoring engine from the Jenkins Maven repository

README.adoc, example/.gitignore, example/agent/Dockerfile, example/agent/jenkins-agent, example/agent/logging.properties, example/docker-compose.yaml, example/jenkins/Dockerfile, example/jenkins/jenkins.yaml, example/jenkins/plugins.txt
Create an all-in-one demo using Docker Compose.
```
$ docker-compose up
```
This will set up
- Jenkins controller
- preconfigured with JCasC
- Jenkins inbound agents
- instrumented with our monitoring engine
- OpenTelemetry Collector
- Loki for Log aggregation
- Prometheus for metric backend
- Grafana for log and metric visualization
- data source is already configured
=> All-in-one demo using Docker Compose

README.adoc
Create Kubernetes demo at https://github.com/Aki-7/remoting-opentelemetry-kubernetes-demo using minikube.
I created it in a separate repository because I want to use the `ghcr.io` Docker registry, and it needs additional permission in "jenkinsci" organization. (repository-local docker registry,`docker.pkg.github.com`, doesn't allow users to pull image without authentication to GitHub)
So I created a demo repository in my account, and add a reference to the repository.
=> Add reference to the kubernetes demo

README.adoc, example/agent/Dockerfile, example/docker-compose.yaml, example/jenkins/plugins.txt
1. Rewrite README in the way we don't need to update the content every time new version of the plugin released.
2. Update Getting started section and instruct uses to install this plugin to the Jenkins controller.
=> Update Getting started documentation.
